#!/usr/bin/env python3
# Work-name:		SSE CLA - Sephs Skyrim Experimental Crash Log Analyzer
# Release-name:	 CLA SSE
# -----------------------------------------------------------------------------
#
# Created: 2023.04.22 by Sephrajin aka sri-arjuna aka (sea)
# Licence: GPLv2
# Source code:	  https://github.com/sri-arjuna/SSE-CLA
# Nexus Mod page:   https://www.nexusmods.com/skyrimspecialedition/mods/89860
#
# -----------------------------------------------------------------------------
#
# In no way I claim this to be either perfect, nor functional,
# it should only assist you to help getting an indication of what MIGHT be wrong,
# without any guarantee that this actually is the cause of the crash.
#
# -----------------------------------------------------------------------------
#
######################################
### Script Variables
######################################
script_name = "CLA SSE - Sephs Skyrim Experimental Crash Log Analyzer"
script_version = "1.0"
script_changed = "2023.06.27"
script_title = script_name + " (" + script_version + ") / " + script_changed
######################################
### Python Version Check
######################################
import sys
if sys.version_info < (3, 3):
	print("This script requires Python 3.3 or higher.")
	print("Please download and install it from https://www.python.org/downloads/")
	sys.exit(1)
######################################
### Imports
######################################
import os
import re
import time		## Not really required, but otherwise we get 0 files on tqdm's progressbar..
import __main__ ## Is this one really required? - we'll see
from cpuinfo import get_cpu_info				# pip install py-cpuinfo
from multiprocessing import freeze_support		# pip install multiprocessing
from tqdm import tqdm							# Progress bar
######################################
### Dictionaries
######################################
# Skyrim SE
simple_Skyrim = {
	'0CB748E': "Have you closed Skyrim 'from the outside' aka with Taskmanager? -- Verification appreciated.",
	'12FDD00': "Probable Callstack: BSShader::unk_xxxxxxx+xx mentioned FIRST or with the HIGHEST PRIORITY\nBroken NIF\nBest apporach, disable some of your NIF mods and figure out which one is causing it by starting a new game to reproduce the error, once figured, report to the mod author so they can create a fix.\nOR, use CAO(Cathedral Assets Optimizer), but that could lead to other issues.. so... its up to you.",
	'12F5590': "Facegen issue:\nRegenerate the Face in CK, search for 'BSDynamicTriShape' as a hint, or check the  HDT-SMP log for the last NPC used. You might need to increase the log level if you havent dont so already.",
	'132BEF': "Head Mesh Issue:\nCheck the HDT-SMP log where the last NPC most probably could be the issue.\nIf you use 'Ordinary Women', make sure that mod gets loaded last among mods that change body/heads.",
	'5999C7': "Monster Mod.esp\nNumerous errors and causes of CTD, even with the unoffical patches and latest updates of the mod itself.\nTo keep it short: Do not use.",
	'5E1F22': "Missing Master (esm):\nGet/fix your mod list in order... dammit!\nEither mod manager should have warned you about this issue!",
	'67B88B': "Probably related to: Callstack: 'AnimationGraphManagerHolder'\nFor now, make sure to regenerate animations using FNIS or Nemesis and NEVER delete FNIS.esp, as that file is generated by either of the two.",
	'7428B1': "Install 'SSE Engine Fixes.\nIf you do have that, are you using the'Equipment Durability System mod'?\nIt could be related to an enchanted weapon braking, or other mods that change a character while holding a weapon.",
	'8BDA97': "This could be an issue of having both, 'SSE Engine Fixes' and 'SSE Display Tweaks' mods active.\nCheck their settings and/or disable one or the other to see if you get another crash - or avoid this from now on.",
	'A': "(probably:) Animation Issue:\nNo further information available",
	'A0D789': "Did you fight a dragon? Did he stomp?\nIf you're using 'Ultimate dragons' there's a fix on its Nexus page.\nIt could also be a DAR issue, please make sure that the animation is not being overwritten.",
	'C0EB6A': "Actualy an issue of SkyrimSE.exe:\nShould be fix-able by the use of 'SSE Engine Fixes' mod",
	'C1315C': "controlmap.txt...What have you done?!\nProbably some mod that uses hotkeys might have modified this file... good luck with the hunt!",
	'D02C2C': "Monster Mod.esp\nNumerous errors and causes of CTD, even with the unoffical patches and latest updates of the mod itself.\nTo keep it short: Do not use.",
	'D2B923': "Save game issue:\nCould be related to either: Save System Overhaul(SSO) or users of the mod Alternate Start-LAL\nMaybe also related to or fixable by SkyUI SE - Flashing Savegame fix",
	'D6DDDA': "Stack: BSResource::anonymous_namespace::LooseFileStream* OR BSResource::ArchiveStream* OR BSResource::CompressedArchiveStream**\nEither you do not have a pagefile that is large enough, or there is an issue with a texture of one of your mods. ",
}
# Skyrim VR
simple_VR = {
	'0B7D4DA': "Could be related to 'View yourself VR' or PLANCK (Physical Animation and Character Kinetics)",
	'ViewYourselfVR.esp': "Has been reported to cause CTD and other bugs.\n\tIf this CTD happened when opening your inventory, try downgrading to 1.1.\n\t - https://www.nexusmods.com/skyrimspecialedition/mods/16809",
}
# Both
simple_Chance = {
	'skse64_loader.exe': "At best, this entry is an indication that the culprint is a mod that is using SKSE...",
	'SkyrimSE.exe': "This file on its own is not the cause, however, we'll do further parsing...",
	'skse64_loader.exe': "At best, this entry is an indication that the culprint is a mod that is using SKSE...",
	'SkyrimSE.exe': "This file on its own is not the cause, however, we'll do further parsing...",
	'SkyrimVR.exe': "This file on its own is not the cause, however, we'll do further parsing...\n\tBe aware, VR has a lot fewer players, so much less issues are covered...",
	'skee64.dll': "Some mod might be incompatible with RaceMenu, or your body.\n\tYou might want to read:\n\t -  https://www.nexusmods.com/skyrimspecialedition/articles/1372 \n\t - https://www.nexusmods.com/skyrimspecialedition/mods/44252?tab=description\n\tIf there are any further entries below this, it might be a strong indicator for its cause.\n\tAlso, please make sure to have this installed:\n\t- Race Compatibility: https://www.nexusmods.com/skyrimspecialedition/mods/2853",
	'Trishape': "Trishapes are related to meshes, specifically a mod supplying a bad mesh. ",
	'NiNode': "Ninodes are related to skeletons. It could be a wrong loadorder for skeleton based mods.\n\tIf you use HDT/SMP, make sure to load it like: Body (CBBE or BH/UNP) -> FNIS/Nemesis -> DAR -> HDT -> XP32\n\tAlso make sure that you've chosen the HDT/SMP variant of xpmsse.\n\tIf you find a mod name in the following list, try disabling it and rerurn FNIS or Nemesis.",
	'mesh': "Some generic mesh issue, yet to be defined...\n\tIf there are any 'indent' lines, they might give a more precice of what _could_ be the reason.\n\t-- This is beta detection, and might not be accurate --\n\t-- This is showing previous lines 1 & 2, and is considered WIP --",
	'hdtSMP64.dll': "If this appears often, it might indicate a bad config (rare). However, it might also just indicate that there were NPCs around that were wearing hdt/SMP enabled clothing...\n\tPlease increase the log level for hdtsmp64 (if you have not done so yet) and check its content.\n\tMake sure to have Faster HDT-SMP that suits your Skyrim Version:\n\t- https://www.nexusmods.com/skyrimspecialedition/mods/57339 \n\tAlso make sure you have these installed:\n\t- SMP NPC fix: https://www.nexusmods.com/skyrimspecialedition/mods/91616 ",
	'cbp.dll': "If this appears often, it might indicate a bad config (rare). \n\tHowever, it might also just indicate that there were NPCs around that were wearing SMP/cbp enabled clothing...\n\tMake sure to have this installed:\n\t\n\t- SMP NPC fix: https://www.nexusmods.com/skyrimspecialedition/mods/91616 ",
	'bad_alloc': "100% your issue! Free RAM, buy more RAM or increase the swap-file (pagefile)... either way, this IS the cause!\n\tTry this:\n\t\t- https://learn.microsoft.com/en-us/sharepoint/technical-reference/the-paging-file-size-should-exceed-the-amount-of-physical-ram-in-the-system",
	'no_alloc': "Could not find the proper memory allocation provided by reference\n\tIf this happens often, you might want to run a 'MemCheck' to check your RAM for faulty hardware.",
	#' Dawnguard.esm': "Your missing the required DLC!\n\tThis might be a false-positive, or not... Needs further investigation!",
	#' Dragonborn.esm': "Your missing the required DLC!\n\tThis might be a false-positive, or not... Needs further investigation!",
	#' Hearthfire.esm': "Your missing the required DLC!\n\tThis might be a false-positive, or not... Needs further investigation!",
	'SchlongsOfSkyrim.dll': "Dont esl'ify any mod that uses Schlongs. Use a previous save and re-schlongify all armors in MCM.",
	'nvwgf2umx.dll': "Update your NVidia driver!\n\tOr your PC is too weak - aka - try fewer / lighter mods.",
	'0x0 on thread ': "This actualy is an engine issue of Skyrim, but rare.\nMost often caused by 'Face lighting' / 'Face shadow' issues. Best chance to avoid: Make sure have the newest SSE Engine Fix!\nNow parsing some keywords that might (or not) give some additional indiciation.",
	'HUD': "There seems to be an issue with your HUD / UI.\n\tNordic UI using the TDM patch might be the cause (at the very least in combination with Skyrim Souls).\n\tIf that is not what you are using, please figure out a fix and send me your crashlog and solution.",
	'tbbmalloc.dll': "Threading Building Blocks Memory Allocator\n\tThis is either part of:\n\t- the CreationKit Fixes: https://www.nexusmods.com/skyrimspecialedition/mods/20061 \n\t- the Engine Fixes (part 2): https://www.nexusmods.com/skyrimspecialedition/mods/17230 \n\n\tMake sure to disable: SrtCrashFix64.dll (Animation Limit Crash fix SSE) as this is handled by the Engines Fixes, which is recomended to use!\n\tEither way, make sure to have the 'latest' version variant for your Skyrim edition.\n\tHowever, this probably is not the cause, but the causing mod relies on excessive memory handling.",
	'DynamicCollisionAdjustment.dll': "General statement, this one is incompatible with the PLANCK for VR.\n\tWhile the name is tempting and promising, bug reports since october 2022 seems to be left untouched by the mod author.\n\tPlease check your issue with the bugs listed there:\n\t- https://www.nexusmods.com/skyrimspecialedition/mods/76783?tab=bugs\n\n\t",
	'Modified by': "These are only listed as additional hints for probably debugging. If you have no other indicators, this might be worth investigating. \n\tIf you do have other indicators, try to solve those first!\n\tThat said, it is common to have 2-4 mods listed in a row, however, \n\tlists of 5 or more _might_ cause issuses by the sheer amount of what possibly could be overwritten several times.",
	'lanterns\lantern.dds': "If you are using: 'Lanterns of Skyrim II' and 'JK Skyrim' do not install the 'No Lights Patch' since LoS II patch is meant to be used without it.",
	'CompressedArchiveStream': "Indicates an issue with a corrupted texture.\n\tIf the results show a DLC, it is probable that another mod overwrites that texture.\n\tIf you do not get a specific texture name, you might want to extract the according '*.BSA' of any found '*.esp' or '*.esm', that is not a DLC.esm.\n\tHowever, best practice would probably be to disable texture mods that change locations you crashed in."
}
# Dialogue - no detailed description, summarizing in if block
simple_Dialog = {
	'Honed Metal': "todo Honed Meta",
	'Your Own Thoughts': "todo Your Own Thoughts",
	'Swift Service': "todo Swift Service",
}
# Racemenu
simple_Racemenu = {
	'XPMSEWeaponStyleScaleEffect.psc': "todo XPMSEWeaponStyleScaleEffect",
	'agud_system.psc': "todo",
	'BGSHazard(Name: `Fire`': "todo BGSHazard",
	'XPMSE': "todo XPMSE",
	'race': "todo race",
	'face': "todo face",
} 
# Engine
simple_Engine = {
	'Facelight Plus': "- Try 'no facelight' variant",
	'Autoconversation-Illuminate': "- Try 'no facelight' variant for 'Facelight Plus'",
	'ShadowSceneNode(Name: `shadow scene node`)': "Unproven, but could indicate cause by combination of multiple lighting mods.",
	'BSFadeNode(Name: `skeleton.nif`)': "",
	'NiCamera': "Unproven, but could indicate cause by combination of multiple lighting mods.",
}
######################################
### Dictionaries	:	counter+
######################################
# Dynamicly get all dictonairies into one list
list_all_dict = [name for name in globals() if name.startswith('simple_')]
# Initialize / reset solution counter
count_solution_64 = 0
count_solution_VR = 0
count_solution_All = 0
# Now 'split' count them, make VR specific
for lid in list_all_dict:
	# Expand var to dict:
	dictionary = globals()[lid]
	# Now add amount of entries of each dictionary
	if lid == "simple_VR":
		count_solution_VR += len(dictionary)
	else:
		count_solution_64+= len(dictionary)
	count_solution_All = count_solution_64 +count_solution_VR

######################################
### Functions:		Console Output
######################################
def console_help():
	# Print help
	print("Usage: CLA_SSE.py [\"C:\some dir\\to\\logs\"]")
	os.system("pause")
	sys.exit(1)

def console_Header(total_Skyrim=0, total_VR=0):
	"""Prints basic disclaimer-heading on the console"""
	print("=====================================================================================")
	print("THE SCRIPT MUST BE IN THE SAME FOLDER AS YOUR CRASH LOGS, WHICH MUST BE 'crash-*.log'")
	print("Usualy this is:		  %userprofile%\Documents\My Games\Skyrim Special Edition\SKSE")
	#print("-------------------------------------------------------------------------------------")
	#print("If you get an error 'File not found', make sure that have applied the exception for")
	#print("this script to allow it to have read/write access within this folder.")
	print("=====================================================================================")
	print("Covered issues/topics on Skyrim: ", total_Skyrim, "\t\t\tSkyrim VR specific issues:", total_VR)
	print("=====================================================================================")

######################################
### Functions:		File Output
######################################
def p_title(str):
	"""Print regular title strings with an underline"""
	print(str)
	print("-" * len(str) + "\n")

def p_section(str):
	"""Print string with a line of # on top and bottom"""
	print("\n" + "#" * 80)
	print(str)
	print("#" * 80 + "\n")

def p_debug_status(debugList, iCount=0, iSolved=0):
	"""Shows statistic & closing debug info"""
	p_section("Success Statistic: (this has been detected/handled, does not mean it's the cause)")
	print("Issues Found:\t" + str(iCount) + "\nIssues Solved:\t" + str(iSolved))
	p_section("DEBUG State:")
	print("Culprit list content: (just a list)")
	c_list = ""
	for s in debugList: print(s + ", ", end="")

def show_Simple(itm, logfile,ShowDivider=True):
	"""Check dict's for itm and prints the according entry, 
	while printing nice 'section'"""
	if ShowDivider: print("-" * 80,"\n")
	# Print simple solution
	for lad in list_all_dict:
		# Expand var to dict:
		d = globals()[lad]
		if itm in d:
			print(itm + ": " + s_Count(itm,logfile))
			print("\t" + d[itm])
			return

######################################
### Functions:		Strings & Lists
######################################
def s_Count(txt, log):
	"""Returns 'count' of 'txt' found in 'log'"""
	count = 0
	for line in log:
		if txt in line:
			count += 1
	return "(count: " + str(count) + ")"

def list_add(item, list) -> list:
	"""Add item to a list."""
	if item not in list:
		list.append(item)
	return list

def list_remove(item, list) -> list:
	"""Remove item from a global list"""
	if item in list:
		list.remove(item)
	return list

def print_line(line2print, list2add, prefix=""):
	"""Print line if not printed yet and add to list2add """
	if line2print not in list2add:
		list2add.append(line2print)
		print(prefix + line2print)

def get_crash_logs(logdir='.') -> list:
	"""Get Crash logs that do not have a report yet."""
	pattern = re.compile(r'crash-.*\.log$')
	patternR = re.compile(r'crash-.*REPORT\.txt$')
	# Make sure logdir is a directory
	if os.path.isfile(logdir):
		logdir = os.path.dirname(logdir)
	# Use list comprehension to create a list of files that match the pattern
	files = [os.path.join(logdir, f) for f in os.listdir(logdir.strip()) if os.path.isfile(os.path.join(logdir, f)) and pattern.search(f)]
	reports = [os.path.join(logdir, f) for f in os.listdir(logdir.strip()) if os.path.isfile(os.path.join(logdir, f)) and patternR.search(f)]
	return files	## TODO: Remove when rewrite is done
	# Remove any log that already has a "-REPORT.txt" file
	with tqdm(total=len(files), desc="Removing duplicates", unit="Report") as progress_bar:
		for f in files.copy():
			report_file = f.removesuffix(".log") + "-REPORT.txt"
			if report_file in reports:
				progress_bar.update(1)
				time.sleep(0.0000000000001)
				files.remove(f)
	return files

def get_version_Mod(str_Mod) -> dict:
	"""Parses str_Mod for regex based on prefix and suffix, then returns:
	full, major, minor, build numbers"""
	str_work = ""
	full_tmp = ""
	dict_ver = {}
	# Prepare string
	exp = r"(?:(64_)?)((\d+[\._]){2}\d+)"
	str_work = re.search(exp, str_Mod).groups()
	full_tmp = str_work[1]
	# Split to sub sections
	if "_" in full_tmp:
		dict_ver["Major"] = full_tmp.split("_")[0]
		dict_ver["Minor"] = full_tmp.split("_")[1]
		dict_ver["Build"] = full_tmp.split("_")[2]
	elif "." in full_tmp:
		dict_ver["Major"] = full_tmp.split(".")[0]
		dict_ver["Minor"] = full_tmp.split(".")[1]
		dict_ver["Build"] = full_tmp.split(".")[2]
	else:
		print("Error: \nCould find neither '.' nor '_' as seperator in string:\n" + full_tmp)
		return None
	# Print proper "full"
	dict_ver["Full"] = dict_ver["Major"] + "." + dict_ver["Minor"] + "." + dict_ver["Build"]
	# Return dictionary
	return dict_ver

##################################################################################################################
### Main Function
##################################################################################################################
def main(file_list):
	"""Get additional cpu info, loop all files and start related functions"""
	# Variables
	files_max = len(file_list)
	files_cur = 0
	# Multiprocess avoidance
	if __name__ == '__main__':
		freeze_support()
		info_cpu = get_cpu_info()
	# Start parsing passed files:
	for thisLOG in file_list:
		files_cur += 1
		print("\n" + str(files_cur) + "/" + str(files_max) + " " + os.path.basename(thisLOG)) # + "\n")
		# Reset variables 'per file'
		culprints = []
		CrashLogger = "Unkown"
		MODE = "64"
		# Read the contents of the log file
		with open(thisLOG, 'r', encoding="utf-8", errors="ignore") as LOG:
			DATA = LOG.readlines()
			print("\t",end="")
			with tqdm(total=count_solution_All, desc="* Searching...", unit=" culprints") as progress_bar:
				# Expand list of all dictionairies
				for lad in list_all_dict:
					# Expand var to dict:
					d = globals()[lad]
					for itm in d:
						progress_bar.update(1)
						# Just check for culprints
						for culprint_Line in DATA:
							if "modules" in culprint_Line.lower():
								break
							if itm in culprint_Line:
								culprints.append(itm)
			# Some file specific tasks:
			try:
				if "Skyrim" == str(DATA[0].split(" ")[0]):
					CrashLogger = "Crash Logger"
					ver_Skyrim = get_version_Mod(str(DATA[0]))
					ver_Logger = str(DATA[1].strip())
					
					# VR or SSE?
					MODE = DATA[0].split(" ")[1]
				elif "NetScriptFramework" in str(DATA[2].strip()):
					CrashLogger = ".NET Script Framework"
					for SF_Line in DATA:
						# GameLibrary: SkyrimSE
						if "GameLibrary" in SF_Line:
							MODE = SF_Line.split(": ")[1] 
						# ApplicationVersion: 1.5.97.0
						if "ApplicationVersion" in SF_Line:
							ver_Skyrim = get_version_Mod(SF_Line.split(": ")[1])
							break
						#ApplicationName: SkyrimSE.exe
			except Exception:
				# Print error and exit
				print("Fatal:\n\tCould not detect CrashLogger. Please use:\n\thttps://www.nexusmods.com/skyrimspecialedition/mods/59818")
				os.system("pause")
				sys.exit(1)
			finally:
				# Apply to both, if and elif...
				# Get SKSE version
				first_pass_str = ''.join(DATA)
				ver_SKSE = re.search("skse.*\.dll", first_pass_str)
				ver_SKSE = get_version_Mod(ver_SKSE.group(0))
				
				# Unhandled Exception
				#line_Unhandled = re.search(r"^Unhandled(\snative)?\s+exception", first_pass_str)
				line_Unhandled = re.search(r"Unhandled(\s+native)?\s+exception.*", first_pass_str)
				if line_Unhandled:
					line_Unhandled = line_Unhandled.group(0)
				else:
					print("Fatal:\n\tCould not detect: 'Unhandled (native) exception")
					os.system("pause")
					sys.exit(1)
				#if not line_Unhandled:
					
				parts = line_Unhandled.split(" at ")
				subparts = parts[1].split(" ")
				#if "0x000000000000" == subparts[0]:
				if 6 >= len(line_Unhandled.split(" ")):
					print("here")
					thisMEM = subparts[0]
					# TODO, skip this for now!
					# culprint.append("0x0")
					thisFile = "n/a"
					thisFileAdd = "n/a"
					thisAssembler = "n/a"
				else:
					thisMEM = subparts[0]
					thisFile = subparts[1].split('+')[0]
					thisFileAdd = subparts[1].split("+")[1][:7]
					if len(parts) >= 1:
						if "\t" in parts[1]:
							thisAssembler = parts[1].split("\t")[1]
							#continue
						elif " " in parts[1]:
							thisAssembler = parts[1].split(" ")[1]
							#continue
						else:
							thisAssembler = "n/a:: "+parts[0]
					else:
						thisAssembler = "n/a"
				
		# Lets open the report for writing
		thisReport = thisLOG.removesuffix(".log")  + '-REPORT.txt'
		#with open(thisReport, "w", encoding="utf-8", errors="ignore") as REPORT:
	#print(ver_SKSE)
	return

			
			# Open output stream
	#		

######################################
### Variables
######################################
script_path = os.path.dirname(os.path.abspath(sys.argv[0])) or None
# If true, cant have arguments (local only), if false, it might - but then needs another path detection
contains_path = bool(script_path)
logdir = None
ver_Skyrim = {}
ver_SKSE = {}
ver_HDTSMP = {}

# Do path detection if required:
if contains_path:
	args_possible = False
	work_dir = script_path
else:
	args_possible = True
	work_dir = os.path.dirname(os.path.abspath(__file__))

######################################
### Start stuff
######################################
# Get args first
if len(sys.argv) == 2:
	if os.path.isdir(sys.argv[1]):
		logdir = sys.argv[1]
	else:
		console_help()
		os.system("pause")
		sys.exit(1)
else:
	logdir = work_dir
# This should retrieve files, 
# and raise exception if permission is missing.
try:
	workfiles = get_crash_logs(logdir)
except Exception:
	# Practical tests show, this is raised on permission issue:
	print("\nPermissionError:\n\tPath exists, but you have no permission to it:\n\t"+logdir)
	print("\nPlease check your Windows security notifications (next to the clock in the taskbar).\n")
	os.system("pause")
	# Need exit to avoid follow up issues...
	sys.exit(1)
# Dont call main() if there is nothing to do
if len(workfiles) == 0:
	print("\nEither there are no logs in: \n\t",logdir,"\n\nOr all logs have a Report.\nEither way, nothing to do...\n\n")
	os.system("pause")
	sys.exit(1)
else:
	# Count dictionary solutions and print console header
	console_Header(count_solution_64,count_solution_VR)
	# Start routine / handle file by file
	main(workfiles)


show_Simple("NiNode", "crash-VR---PortableFreezer.log")




# Exit properly
os.system("pause")
sys.exit(1)